import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Template 1",
  description: "Generated by Bluecorp Software PVT LTD.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark:bg-zinc-700">
      <body className={inter.className} suppressHydrationWarning={true} >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
